- hosts: k3s_cluster,loadbalancer
  vars_prompt:
    - name: snapshot_name
      prompt: "Enter snapshot name"
      private: no

    - name: snapshot_description
      prompt: "Enter snapshot description"
      private: no

  tasks:
    - name: Limit block
      when: limit is undefined or item in limit
      include_role:
        role: vm/create_snapshot
      vars:
        vm_name: "{{ inventory_hostname }}"
