---
- hosts: localhost
  tasks:
    - name: Clone k3s servers from template
      include_role:
        role: lab.vmware.clone_vm
      vars:
        vm_name: "{{ hostvars[item].vm_name }}"
        vm_template: "{{ hostvars[item].vm_template }}"
        vm_datastore: "{{ hostvars[item].vm_datastore }}"
      loop: "{{ groups['k3s_cluster'] + groups['loadbalancer'] }}"
      when: limit is undefined or item in limit

    - name: Wait for VMware tools to become available
      include_tasks: tasks/confirm_create_vm.yml
      loop: "{{ groups['k3s_cluster'] + groups['loadbalancer'] }}"

