---
- hosts: k3s_databases
  vars_files:
    - vars/config.yml

  vars:
    k3s_download_url: "https://github.com/k3s-io/k3s/releases/{{ 'tag/' + k3s_release if k3s_release is defined else 'latest' }}/{{ k3s_arch | default('k3s') }}"
    db_name: "{{ node_config.db_name | default(k3s_config.nodes.databases.db_name) | mandatory}}"
    db_username: "{{ node_config.db_username | default(k3s_config.nodes.databases.db_username) | mandatory }}"
    db_password: "{{ node_config.db_password | default(k3s_config.nodes.databases.db_password) | mandatory }}"
    db_ip: "{{ node_config.ip | mandatory}}"
    db_port: "{{ node_config.db_port | default(3306) }}"
    db_url: "node_config.db_url | default('mysql://{{ db_username }}:{{ db_password }}@tcp({{ db_ip }}:{{ db_port }})/{{ db_name }}')"

    # populates node_config with the host vars for the given inventory_hostname the play is running for
    node_config: "{{ k3s_config.nodes.k3s_databases.hosts | json_query(query_string) | first }}"
    query_string: "[? name=='{{ inventory_hostname }}']"

  tasks:
    - name: Get k3s binary
      get_url: "{{ k3s_download_url }}"
        dest: "/usr/local/bin"
        mode: "0754"

    - name: Become block
      become: yes
      block:
