- hosts: storage
  pre_tasks:
    - include_role:
        role: k3s/fetch_kube_config
        apply:
          delegate_to: localhost

  roles:
    - role: k3s/storage

- hosts: worker
  tasks:
    - name: Install apt prereqs
      become: yes
      ansible.builtin.apt:
        name:
          - open-iscsi
        update_cache: yes

    - name: Ensure open-iscsi is running
      become: yes
      ansible.builtin.systemd:
        name: iscsid
        state: started

- hosts: localhost
  vars:
    longhorn_manifest_path: "{{ playbook_dir }}/files/longhorn.yaml"

  tasks:
    - name: Add the Longhorn Helm repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io

    - debug: var=kube_config_file

    - name: Install Longhorn in the longhorn-system namespace
      kubernetes.core.helm:
        name: longhorn
        kubeconfig: "{{ playbook_dir }}/files/kube_config.yml"
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: yes
        update_repo_cache: yes
        validate_certs: no
        values_files: "{{ playbook_dir }}/files/longhorn_values.yml"
        force: yes

    - name: Remove local-path storage from default storageclass
      command: "kubectl patch storageclass {{ storage }} --kubeconfig {{ kube_config_file }} -p '{{ patch }}'"
      vars:
        storage: local-path
        patch: '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
