- hosts: k3s_cluster,loadbalancer
  tasks:
    - name: List snapshots
      when: limit is undefined or item in limit
      include_role:
        role: vm/list_snapshots
      vars:
        vm_name: "{{ inventory_hostname }}"
