- hosts: k3s_cluster,loadbalancer
  vars_prompt:
    - name: snapshot
      prompt: Enter snapshot name:(leave blank for latest)     
      private: no

  tasks:

    - name: Limit block
      when: limit is undefined or item in limit
      include_role:
        role: vm/restore_snapshot
      vars:
        snapshot_name: "{{ '__LATEST__' if snapshot.user_input | default(snapshot) == '' else snapshot.user_input | default(snapshot) }}"    
